# Generated by Django 4.1.3 on 2023-01-22 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starscience', '0004_alter_article_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_area', models.CharField(max_length=200)),
                ('knowledge_sub_area', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='knowledgesubarea',
            name='knowledge_area',
        ),
        migrations.DeleteModel(
            name='KnowledgeArea',
        ),
        migrations.DeleteModel(
            name='KnowledgeSubarea',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starscience.category'),
        ),
    ]
