# Generated by Django 4.1.2 on 2023-01-26 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starscience', '0007_alter_article_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='knowledge_area',
        ),
        migrations.RemoveField(
            model_name='category',
            name='knowledge_sub_area',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starscience.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
