# Generated by Django 4.1.2 on 2023-07-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starscience', '0008_remove_category_knowledge_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savearticle',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
